### ISSUE TITLE
Перевод мудрой каровы

### ISSUE THREAD

**Issue by BR54FF** [ss220club/Bandastation#137]
Ы

**Comment by VaskaPepelov** [comment]
Ы

**Comment by VaskaPepelov** [comment]
Первая 101 строчка. Что то перевёл в лоб, что то чуть чуть изменил, что то полностью перелопатил.

Это день для уверенных решений!!!!! или нет?
Пройдёт пару часов и безумие начнётся снова.
Скоро вам будет сделан подарок в виде цветка.
Скоро к вам явится давно забытая любовь.
Высокий, мрачный незнокомец будет веселиться больше вашего.
Посещение нового места повлечёт странную работу.
Посещение странного места повлечёт новую работу.
Вас характеризует живой и творческий ум.
Оставь поиск истины; довольствуйся хорошей фантазией.
Подчеркни полезную сторону своей натуры. Откачай выгребную яму.
Вас ждёт повышение.
После того, как ваш возлюбленный уйдет, у вас все равно останется РАМЕН ОТ ГОСПОДИНА ЧАНГА, ВСЕГО ЗА 10, 99!
Запомни, тигр всегда прав, если нет, то он лев.
Алименты и взятки составят значительную часть вашего состояния.
Все ваши неприятности, как по щелчку, исчезнут.
Среди счастливчиков, ты - избранный.
Холодильник авокадового оттенка будет хорошо смотреться в вашем резюме.
В вашем будущем вас ждет экзотическое путешествие по центру Ньюарка.
Еще одна хорошая ночь, чтобы не спать в камере предварительного заключения.
Ты черепаха?
Ты когда-нибудь будешь мыть посуду? Или сменишь специальность на биологию?
Ты на ходу этот бред придумываешь?
Ты не забыл закрыть входную дверь?
Твоя тяга к прекрасному не осталась незамеченным. Ограбь музей.
Избегайте недоразумений с помощью спокойствия, уравновешенности и сдержанности.
Избегайте стрельбы в туалете сегодня вечером.
Избегайте реальности любой ценой.
Банковская ошибка в вашу пользу. Получите 200 долларов.
Будь осторожен! Это засекречено?
Сходи, умойся и волосы причеши.
Будьте осторожны в своих повседневных делах.
Будь жизнерадостным, пока вы живы.
Не смей никому подчиняться, как понял?
Будьте свободны, открыты и жизнерадостны! Наслаждайтесь! Лучше уже не станет, так что привыкай к этому.
Будьте внимательны к безопасности - на карту поставлена национальная безопасность.
Красота и гармония необходимы вам так же, как само дыхание жизни.
Высшее благо - никогда не рождаться. Великое благо - поскорее умереть.
Лучше надейся, что инспекция не нагрянет, пока твоя жизнь в таком упадке.
Остерегайтесь темноволосого мужчины с ярким галстуком.
Остерегайтесь высокого чернокожего мужчины в одном светлом ботинке.
Остерегайтесь высокого блондина в одном черном ботинке.
Остерегайтесь снежного человека!
Остерегайтесь низко летающих бабочек.
Остерегайтесь того, кто стоит у вас за спиной.
Закрой рот, воняет.
Ворвись в тюрьму и заяви о полицейской жестокости.
Впереди мост. Заплати троллю.
Ты таков таким, каким ты есть и больше не каким.
Внимание: дыхание может быть опасным для вашего здоровья.
Внимание: Храните в недоступном для детей месте.
Отпразднуй в этом году день каннибала. Пригласи на обед слона.
Измените свои мысли, и вы измените свой мир.
Не унывайте! Мир катится в бездну чууть медленнее чем вчера.
Шляпку гриба нужно есть первой.
Смерть одного человека - это трагедия; смерть двух миллионов это статистика.
Он был прав.......
Следуй за пауками.
Общайтесь! Хуже от этого не станет.
Мужество - это ваша самая большая потребность в данный момент.
День проведения расследования. Вы будете вызваны в суд.
Не переоценивайте свои силы.
Не спи сегодня ночью на эвкалиптовом дереве.
Ничего не делай без крайней необходимости, а когда припрёт - мешкай.
Сделай сегодня что-нибудь необычное. Оплати счет.
Делайте то, что приходит само собой. Кипите от злости и устраивайте истерики.
Семейное счастье и верные друзья.
Не корми сегодня летучих мышей.
Не застревайте в шкафу - это изнурит вас.
Не надо хвастаться.
Запомни, а то забудешь.
Безумно можно быть первым.
Не надо ненавидеть себя по утрам - спи до полудня.
Не целуй сегодня слона в губы.
Не позволяй своему разуму блуждать - он слишком мал, чтобы его можно было оставить без присмотра.
Не оглядывайся, лемминги настигают тебя.
Ты не знаешь, но человек на Луне смеется над тобой.
Не дёргайся, но у тебя на плече сидит многоногое существо.
Не планируйте поспешных действий. Вас все равно скоро выселят.
Не читай никаких надписей на небе в течение следующих двух недель.
Не читайте все, во что верите.
Не говорите сегодня большой лжи. Маленькая ложь столь же эффективна.
Не волнуйся так громко, твой сосед по комнате не может думать.
Don't Worry, Be Happy.
Не волнуйся. Жизнь слишком длинная.
Разве сейчас ты не чувствуешь себя лучше, чем тогда, когда пришел?
Разве вы не хотели бы, чтобы у вас было больше энергии?.. или меньше амбиций?
Все, что ты знаешь, неверно, но ты можешь исправиться.
Сегодня все будет просто тип-топ.
Отличный день для того, чтобы пускать пружинки с эскалатора.
Отличный денек для того, плохого дня.
Отличное время для того, чтобы стать пропавшим без вести.
В вашем характере заметны исполнительные способности.
Проявляйте осторожность в своих повседневных делах.
Ожидайте письма от друга, который попросит вас об одолжении.
Ожидай худшего, это самое малое, что ты можешь сделать.
Прекрасный день для друзей. Для тебя день так себе.
Прекрасный день для того, чтобы заняться спортом. Укради что-то тяжелое.
Предсказание: В следующую среду в 15:15 на вас нападут шесть самураев с фиолетовыми рыбками в руках, приклеенными к мотоциклам Harley-Davidson. И хорошего дня!
Будущее туманно. Поздним вечером вы прольете суп.
Щедрость и совершенство - вот ваши недостижимые цели.
Дайте ему уклончивый ответ.
