### ISSUE TITLE
Трейт Family Heirloom не сохраняется.

### ISSUE THREAD

**Issue by Alex8919** [ss220club/Bandastation#172]
### Описание проблемы

Трейт просто сбрасывался, когда переключался на другие вкладки в создании персонажа, в раунде так же был без реликвии.

### Что должно было произойти?

Трейт должен сохраниться во вкладке со взятыми трейтами.

### Что случилось вместо этого?

Трейт сбрасывается

### Шаги для повторения проблемы.

Берем трейт Family Heirloom
Переключаемся между вкладками
Наблюдаем, что трейт не сохраняется во вкладке с взятыми трейтами

### Когда проблема началась?

Сегодняшний тест(20.04.24)

**Comment by larentoun** [comment]
ТГ кодер-момент. Квирки, влияющие на муд, отключены, когда муд выключен, но в ТГУИ всё ещё отображаются.
