### ISSUE TITLE
Не хватает микшера громкости отдельно взятых звуков

### ISSUE THREAD

**Issue by dj-34** [ss220club/Bandastation#190]
Проблема которые могли бы быть решены микшером.
1. ОЧЕНЬ ГРОМКИЙ эмбиент станции, изза которого приходится полностью его отрубать (а не хочется).
2. Звуки фаер алярмов.

**Comment by Gaxeer** [comment]
На оффы сразу будем делать

**Comment by Gaxeer** [comment]
Оффы вроде сделали. Нормас
