### ISSUE TITLE
Что требуется для открытия / Стримерские запросы

### ISSUE THREAD

**Issue by dj-34** [ss220club/Bandastation#221]
**Запросы Мунивёрса:**

- [x] 1. Выпилить местоимения Они/Их и подобное (стоит ли упоминать прайд пины вновь? хдд)
- [x] 2. Выпилить/заменить на что-то другое "рпшные" дроп поды, как например заказ инструментов у квирка музыканта.
- [ ] 3. Расы с Парадайза (в первую очередь Таяры, Вульпы, Воксы).
- [x] 4. Ввести переведенную Википедию ТГ (хотя бы основное).
- [ ] 5. Огромные персонажи выглядят неуместно (обожрались хуйни и спрайты выросли x4).

**Для штатного открытия:**

- [x] 1. Снизить хаос в конфиге (на 60 ебл: маг, ксеноморфы, 2(?) трейтора и еще кто-то).
- [ ] 2. Привязка Дискорда.
- [ ] 3. Общая БД по банам, привязкам(?).
- [ ] 4. Генерация чейнджлогов (не так важно).
- [ ] 5. Починить ТТС (отсутствие эффектов у мегафона, отсутствие новых голосов).

**Comment by PhantornRU** [comment]
Поды стоит заменить на блюспейс телепортацию. Можно с созданием маленьких БС порталов. Можно еще пихать в ящики.
А если кто-то будет стоять на месте "приземления" блюспейс ящика, то его самого запихнет в ящик. Jokerge

Пока пробую портировать модульные расы с МанкиСтейшина. Будут добавлены Флораны (дионы) и КПБ. Еще куча рас для щитспавна станет доступно. Но только для щитспавна, открывать их пока не будем. Также попытаюсь сразу адаптивную одежду с манкистейшина скомуниздить.

Огромные персонажи кринж. То же самое видел на манкистейшине. Большие борги из-за этой хуйни - тоже кринж.
