### ISSUE TITLE
[Баг] Шпион и исчезновение глаз.

### ISSUE THREAD

**Issue by TeenWo1f** [ss220club/Bandastation#266]
### Описание проблемы

Когда Шпион ворует глаза у человека, глаза исчезают, но человек не слепнет, а видит всё также, как и раньше.

### Что должно было произойти?

При выполнения задания на кражу глаз у человека, этот человек должен ослепнуть.

### Что случилось вместо этого?

Как будто ничего и не изменилось. Глаза у человека исчезли, но видел он всё также, как и с глазами.

### Почему это плохо/Какие последствия?

Игроки могут даже и не понять, что у них украли глаза, так как геймплей у них никак не изменяется.

### Шаги для повторения проблемы.

Получить задания за Шпиона на кражу глаз у персонала. Усыпить его(усыплял с помощью баллона, заполненным полностью на сонный газ). Когда человек спал, начал кражу глаз с помощью пда. К концу кражи человек проснулся и произошла кража.

### Когда проблема началась?

Было замечено мной 12 мая.

**Comment by larentoun** [comment]
Если проблема всё ещё присутствует, создайте ишуе снова
