### ISSUE TITLE
Вернуть возможность отрубить голову

### ISSUE THREAD

**Issue by Gaxeer** [ss220club/Bandastation#315]
https://github.com/tgstation/tgstation/pull/80703 в данном ПРе убрали отрубание головы, заменив на травму. Стоит вернуть это

**Comment by larentoun** [comment]
Нет необходимости. Нет целей на голову. Глаза можно вытащить рукой, если голова в труху (полный урон, травма раскола черепа).

Если прям хочется отрезать - бензопила может отрезать, как и ножницы для ампутаций
