### ISSUE TITLE
Сломался оверлей консолей

### ISSUE THREAD

**Issue by dj-34** [ss220club/Bandastation#364]
Сломался оверлей консолей, возможно после перевода профессий/департаментов 👍 

(Были красные экранчики, стали серые)
![image](https://github.com/user-attachments/assets/b1e0d281-8051-4af5-8d77-b8f51f09dcfd)

**Comment by larentoun** [comment]
![image](https://github.com/user-attachments/assets/1100a4d9-2399-42ec-b0c4-167850c248e1)

На момент билда на сервере, это мастер ТГ
