### ISSUE TITLE
Отключить ивент с рандомным карго подом и синди лутом

### ISSUE THREAD

**Issue by Furrior** [ss220club/Bandastation#39]

**Comment by Lime-7** [comment]
No description provided. клюлес

**Comment by Furrior** [comment]
> No description provided. клюлес
> 

Если тебе по названию непонятно, то описание не поможет

**Comment by Lime-7** [comment]
> > No description provided. клюлес
> 
> Если тебе по названию непонятно, то описание не поможет

мне то по названию все понятно, но обычно  в описании так же пишут причину для чего нужны изменения. клюлес

**Comment by Gaxeer** [comment]
Stray cargo pod сделали гибающим и пробивающим обшивку. Так что норм. 
![image](https://github.com/user-attachments/assets/5e4e524a-81dd-415b-bcca-3160d3b5edcf)
