### ISSUE TITLE
При смене голоса, голос пропадает

### ISSUE THREAD

**Issue by AyIong** [ss220club/Bandastation#486]
### BYOND Version

Не важно

### Описание проблемы

Если сменить голос через VV, голос у чела исчезнет
Плюс, скорее всего не то окно выбора голоса, и может открыться несколько списков с выбором голоса

### Шаги для повторения проблемы.

Сменить голос через VV

### Когда проблема началась?

ТМ рефактора ТТС

### Дополнительная информация

Компоненту присваивается effects числом, хотя должен быть пустой список если эффектов нет

**Comment by larentoun** [comment]
Откройте снова, если не работает
