### ISSUE TITLE
Превью у вульп не корректное

### ISSUE THREAD

**Issue by AyIong** [ss220club/Bandastation#493]
### BYOND Version

Не важно?

### Описание проблемы

Игрок при заходе в игру, увидел что его псина выглядит совершенно не так как в меню создания перса
![image](https://github.com/user-attachments/assets/84697b3f-ee90-4584-a4aa-6292969b18af)

### Что должно было произойти?

Превью должно быть честным :aga:

### Что случилось вместо этого?

Превью напиздело

### Шаги для повторения проблемы.

Надо бы посоздавать кукл и посмотреть так же как на превью они выглядят в игре

### Когда проблема началась?

https://github.com/ss220club/Bandastation/pull/267

### Дополнительная информация

Вульпы всё ещё в ТМ

**Comment by larentoun** [comment]
Прикол ТГ
