### ISSUE TITLE
changing appearance by changeling saves flavor

### ISSUE THREAD

**Issue by Graybear98** [ss220club/Bandastation#494]
### BYOND Version

515.1642

### Описание проблемы

Сменил внешность на линге, но флавор остался как у моей основной куклы

### Что должно было произойти?

флавер или исчезнет или возьмется флавер куклы, чей внешностью я прикидываюсь

### Что случилось вместо этого?

флавор мой остался

### Почему это плохо/Какие последствия?

мне в игре произнесли мое описание и сказали Сиси????? я короч спалился

### Шаги для повторения проблемы.

Украсть ДНК у космонавтика
Применить его внешность через абилку

### Когда проблема началась?

Сегодня на запуске обнаружил

**Comment by Deultus** [comment]
Стоит отметить, это не только с лингом, выбрав гостроли антага у вас также останется/появится  ваше старое описание внешности, клоун умер, да здравствует новый клоун
