### ISSUE TITLE
Граф. баг с взрывчаткой по типу С4

### ISSUE THREAD

**Issue by adskipups** [ss220club/Bandastation#546]
### Client Version:

515.1642

### Issue Summary:

При установки взрывчатки на пол должен появится сам спрайт бомбы на тайле, но этого не происходит.
(Также возможно этот баг работает и с другой взрывчаткой(С4, X4 и взрывчаткой из минорной цели агента).

### Round ID:

Не помню, но багу точно есть 3 месяца.

### Reproduction Steps:

1. Стать на любой тайл. 2. Установить заряд взрывчатки(с4 или x4) на пол. 3. После установки спрайт бомбы не будет виден на тайле, но сама взрывчатка там стоит(через контекстное меню видно)

**Comment by larentoun** [comment]
На оффы, мы не меняли
