### ISSUE TITLE
во время рад шторма двери в теха не ставятся на аварийный доступ

### ISSUE THREAD

**Issue by Graybear98** [ss220club/Bandastation#570]
### Client Version:

322.228

### Issue Summary:

После объявления тревоги о надвигающейся волне радиации двери в теха должны перейти на аварийный доступ, чего не произошло и мне по рп стало грустно. На оффах я не замечал проблему, хз, может у вас что то сломано

### Round ID:

хз

### Test Merge Information:

-

### Reproduction Steps:

эвент радшторма
не дождаться аварийных дверей
грустить

**Comment by larentoun** [comment]
Такого нет на оффах
