### ISSUE TITLE
фиксированный уровень трита

### ISSUE THREAD

**Issue by Graybear98** [ss220club/Bandastation#616]
### BYOND Version

515.1642

### Описание проблемы

По какой то причине, после каждого запуска я наблюдаю картину, где всегда 40 трита, либо меньше, я хз, что ограничивает динамик и как ограничивает, но считаю, что так не должно быть

### Что должно было произойти?

трит должен генериться от 0 до 100

### Что случилось вместо этого?

40 трита стабильно

### Почему это плохо/Какие последствия?

смены по задумке должны быть динамичными, спокойными и такими, 50/50, меня в целом устраивает кол-во антагов на тесте, но как будто бы это ошибка и такого быть не должно.

### Шаги для повторения проблемы.

зарегать раунд

### Когда проблема началась?

я точно сказать не могу, летом еще.

### Дополнительная информация

ПРОКЛЯТЬЕ 220

**Comment by larentoun** [comment]
Сейчас условия тестов, и на не частые раунды не очень продуктивно будет сидеть с 10 трита (что было сегодня). Сейчас динамик сильно сдвинут к 40-50 трита на >40% раундов.
