### ISSUE TITLE
Вайшип из космоса нельзя пристыковать к станции кибериада

### ISSUE THREAD

**Issue by Graybear98** [ss220club/Bandastation#861]
### BYOND Version

515.1642

### Описание проблемы

Я нашел вайтшип в космосе и не смог выбрать станцию как точку назначения

### Что должно было произойти?

Я ожидал, что я его пригоню к станции

### Что случилось вместо этого?

Произошла неприятность!

### Почему это плохо/Какие последствия?

На станции нет дока для стыковки вайтшипа, он не влезает

### Шаги для повторения проблемы.

1.Найти вайтшип
2. Найти там консоль
3. Расстроиться

### Когда проблема началась?

На кибериаде началась

**Comment by dj-34** [comment]
Потенциальный фикс https://github.com/ss220club/Bandastation/pull/872
