### ISSUE TITLE
Ошибка ERROR на дверях

### ISSUE THREAD

**Issue by NanimeDesu** [ss220club/Bandastation#885]
### Описание проблемы

Если повесить бумажку, или фото на шлюз будет ERROR

![image](https://github.com/user-attachments/assets/faa44fdb-c537-4518-976f-cd5df806e467)

(Дополнение от @dj-34)

![image](https://github.com/user-attachments/assets/97579be9-ee76-4c87-ade5-565c25fa982a)

### Что должно было произойти?

Не должно быть его

### Что случилось вместо этого?

Ошибка на дверях

### Шаги для повторения проблемы.

Повесить бумажку

### Когда проблема началась?

Тест 20-12-2024 первый раунд

**Comment by dj-34** [comment]
Дополнил твой ишуе
