### ISSUE TITLE
бэкрумс кибериады

### ISSUE THREAD

**Issue by Graybear98** [ss220club/Bandastation#897]
### BYOND Version

515.1642

### Описание проблемы

теха кибериады, верхний уровень, правая часть, там, где ксенобио, из них невозможно выйти, не имея доступ в теха, даже, если у тебя карта ученого

### Что должно было произойти?

я должен был спокойно выбраться из техов, даже не имея доступа к рнд

### Что случилось вместо этого?

мне пришлось делать крюк и выходить у психолога

### Почему это плохо/Какие последствия?

санаби(

### Шаги для повторения проблемы.

зайти в теха правые ксенобио и не смочь выйти

### Когда проблема началась?

ну вот сейчас случилась

### Дополнительная информация

так звучит мой голос

**Comment by CallmeHouston** [comment]
Работа над техами ведется, срок не назову, но техи будут изменены точно

**Comment by Graybear98** [comment]
Мое дело уведомить

**Comment by dj-34** [comment]
Вроде было исправлено
