### ISSUE TITLE
Перенести биоген в стену к повару

### ISSUE THREAD

**Issue by Graybear98** [ss220club/Bandastation#903]
### BYOND Version

515.1642

### Описание проблемы

Очень неудобно быть поваром! Квалити оф лайф

### Что должно было произойти?

Сюзан Доу сделай пожалуйста!

### Что случилось вместо этого?

-

### Почему это плохо/Какие последствия?

Приятный гейминг

### Шаги для повторения проблемы.

-

### Когда проблема началась?

-

**Comment by dj-34** [comment]
Частично решено перенесением биогена в садик
